### ISSUE TITLE
Support customization of HTTP port

### ISSUE THREAD

**Issue by chrisdoherty4** [tinkerbell/smee#317]
# Context

While refactoring the Tinkerbell helm charts it became apparent that customization of the HTTP port Boots uses to serve iPXE artifacts is unsupported by Boots as it does not propagate the port to clients.

# Description

Users don't always want to use port 80 when deploying Tinkerbell as its a popular port number. Boots should fully support customization of the port serving HTTP artifacts for iPXE by propagating the port to the iPXE client.

**Comment by jacobweinstock** [comment]
This is now available. It needs a paragraph in the docs somewhere but here's how to do it.

Generally speaking you would first set `-http-addr` to listen on the desired IP:Port. 

```bash
-http-addr 192.168.2.50:8585
```

Then you would need to update the DHCP flags.

```bash
# This sets the ipxe script url
-dhcp-http-ipxe-script-url http://192.168.2.50:8585/auto.ipxe

# This sets the URL for where iPXE binaries will be served
-dhcp-http-ipxe-binary-ip http://192.168.2.50:8585/ipxe
```
