### ISSUE TITLE
Does smee support binding to IPv6 address ?

### ISSUE THREAD

**Issue by ekatamil** [tinkerbell/smee#433]
We are planning to use tinkerbell as baremetal provisioner for our baremetal servers but upon browsing the DHCP server(smee) code we came to understand that tftp/http and dhcp servers are binding only to IPv4.

Is there a plan to provide IPv6 support in smee in the near future ?
Is the support for IPv6 reserved only for commercial version of tinkerbell ?

## Expected Behaviour

Smee should be capable to binding to both IPv4 and IPv6 address 

## Current Behaviour
Smee is binding only to IPv4 global unicast address.

**Comment by jacobweinstock** [comment]
Hey @ekatamil , thanks for logging the issue. To clarify, are you only interested in interface/address binding? or are you looking for DHCPv6 support too?

**Comment by jacobweinstock** [comment]
Oh also, to be clear, there is no commercial version of Tinkerbell.

**Comment by ekatamil** [comment]
Hi @jacobweinstock,

Thanks for the reply. 
I am expecting both
1 > Should be able to bind to an IPv6 address
2 > Should have DHCPv6 support along with DHCPv4 support.

**Comment by jacobweinstock** [comment]
Hey @ekatamil. Thanks for clarifying. Unfortunately, there are currently no plans to implement DHCPv6. Please feel free to open an issue here: https://github.com/tinkerbell/roadmap/issues if you want to discuss this further.
