### ISSUE TITLE
man page for boots

### ISSUE THREAD

**Issue by vielmetti** [tinkerbell/smee#9]
Provide a man page for `boots`, so that a sysadmin looking for help on command line options, flags, and other issues has a single place to go.

Suggest that the man page be written with markdown + pandoc, as described in [this tutorial](https://eddieantonio.ca/blog/2015/12/18/authoring-manpages-in-markdown-with-pandoc/) - no particular need to write raw troff. The file https://github.com/eddieantonio/license/blob/master/license.1.md is an example written this way.

**Comment by vielmetti** [comment]
This is related to #7 in that documenting the env variables can go in the `ENVIRONMENT` section of the man page.

**Comment by splaspood** [comment]
It seems that we should have consistent standards for CLI/ENV arguments and the documenting thereof.    As much as I have a fondness for man, I wonder if that's really the place where most people will go to find this documentation given today's common deployment methods and use cases.

**Comment by jacobweinstock** [comment]
all the cli flags are documented in the readme. https://github.com/tinkerbell/smee?tab=readme-ov-file#local-setup
